# -*- coding: utf-8 -*-
"""Flutter Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEmR_yNucfmzax96l7y7KzkTIlQB9A4y
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import eig

class FlexibleWing:
    def __init__(self, m=1.0, I=0.5, S=0.05, Kh=100.0, Ka=80.0, c=1.0, rho=1.225):
        self.m, self.I, self.S = m, I, S
        self.Kh, self.Ka = Kh, Ka
        self.c, self.rho = c, rho

    def system_matrix(self, U):
        m, I, S = self.m, self.I, self.S
        Kh, Ka = self.Kh, self.Ka
        c, rho = self.c, self.rho

        # Mass matrix
        M = np.array([[m, S],
                      [S, I]])

        # Structural stiffness
        K = np.array([[Kh, 0],
                      [0, Ka]])

        # Aerodynamic stiffness (quasi-steady)
        Kaero = np.array([
            [0, -2*np.pi*rho*U**2*c],
            [0, -0.5*np.pi*rho*U**2*c**2]
        ])

        # Aerodynamic damping
        Caero = np.array([
            [2*np.pi*rho*U*c, -2*np.pi*rho*U*c*0.3*c],
            [0, 0.5*np.pi*rho*U*c**2*0.2*c]
        ])

        # Convert to state-space: x = [h, alpha, h_dot, alpha_dot]
        zero = np.zeros((2,2))
        I2 = np.eye(2)

        Minv = np.linalg.inv(M)

        A_top = np.hstack((zero, I2))
        A_bottom = np.hstack((
            -Minv @ (K + Kaero),
            -Minv @ Caero
        ))

        A = np.vstack((A_top, A_bottom))
        return A


def find_flutter(wing, U_vals):
    growth_rates = []

    for U in U_vals:
        A = wing.system_matrix(U)
        eigvals = eig(A)[0]
        max_real = np.max(np.real(eigvals))
        growth_rates.append(max_real)

    growth_rates = np.array(growth_rates)

    # Find where it crosses zero
    for i in range(len(U_vals)-1):
        if growth_rates[i] < 0 and growth_rates[i+1] > 0:
            return U_vals[i]

    return None


if __name__ == "__main__":
    wing = FlexibleWing()

    U_vals = np.linspace(1, 100, 200)
    U_f = find_flutter(wing, U_vals)

    print(f"Flutter speed ≈ {U_f:.2f} m/s")

    # Plot growth rate
    growth = []
    for U in U_vals:
        eigvals = eig(wing.system_matrix(U))[0]
        growth.append(np.max(np.real(eigvals)))

    plt.plot(U_vals, growth)
    plt.axhline(0, linestyle='--')
    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Max Real Eigenvalue")
    plt.title("Flutter Detection")
    plt.grid()
    plt.show()

    # Sweep Ka
    Ka_vals = np.linspace(30, 200, 8)
    flutter_speeds = []

    for Ka in Ka_vals:
        wing2 = FlexibleWing(Ka=Ka)
        Uf = find_flutter(wing2, U_vals)
        flutter_speeds.append(Uf if Uf else 100)

    plt.plot(Ka_vals, flutter_speeds, 'o-')
    plt.xlabel("Torsional stiffness Ka")
    plt.ylabel("Flutter speed")
    plt.grid()
    plt.show()